// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7OHYiPkCytyWEcBzSs-A8Dv10S5f4mCo',
    appId: '1:931491206888:android:36915033264edd90ac5b5d',
    messagingSenderId: '931491206888',
    projectId: 'dictionary-e55a4',
    storageBucket: 'dictionary-e55a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEy52NsdY7VvB448P1D6gTxlvByYgtgcU',
    appId: '1:931491206888:ios:5d7ca4750f4451d1ac5b5d',
    messagingSenderId: '931491206888',
    projectId: 'dictionary-e55a4',
    storageBucket: 'dictionary-e55a4.appspot.com',
    iosClientId: '931491206888-d7h86iq9o54c17kf5pjr87639j0cmo9i.apps.googleusercontent.com',
    iosBundleId: 'com.catonknees.dictionary.dictionary',
  );
}
